/**
 * Twenty desensitised SMT / THT project records.
 *
 * Every field is transcribed from the project delivery system. Customer names,
 * pricing and contract part numbers are deliberately absent from the source and
 * must not be added here. Metrics carry the basis they were recorded under:
 *
 * - "Delivery record" dated milestones from the project system
 * - "Measured"       production or field measurement
 * - "Specification"  customer-stated or product specification
 *
 * Source of record: case-studies_SMThelp_20_projects.html
 */

export type MetricBasis = "Delivery record" | "Measured" | "Specification";

export type ProjectCaseMetric = {
  value: string;
  label: string;
  basis: MetricBasis;
};

export type ProjectCaseMilestone = {
  date: string;
  event: string;
};

export type ProjectCase = {
  id: string;
  num: string;
  title: string;
  region: string;
  industry: string;
  status: string;
  statusTone: "done" | "part" | "open";
  recordedWindow: string;
  team: string;
  profile: string;
  image: { src: string; alt: string; sourcePage: string | null } | null;
  background: string;
  challenge: string;
  solution: string;
  implementation: string;
  metrics: ProjectCaseMetric[];
  benefits: string[];
  timeline: ProjectCaseMilestone[];
  evidence: string;
};

export const PROJECT_CASES: ProjectCase[] = [
  {
    id: "case-01",
    num: "01",
    title: "Custom Belt Feeder and Gripper Nozzle for an Installed Placement Platform",
    region: "South America",
    industry: "SMT equipment distribution / EMS support",
    status: "Delivered",
    statusTone: "done",
    recordedWindow: "Jul 2025 - May 2026",
    team: "Jason Wu",
    profile: "A distributor and service house for SMT lines in Brazil, supplying placement equipment, feeders and consumables to regional EMS factories and running its own field service team.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/desc/2015/09/Nozzle.jpg?imageMogr2/thumbnail/960x640/format/webp",
      alt: "Custom SMT nozzles engineered and manufactured for an installed third-party placement platform",
      sourcePage: "https://www.smthelp.com/product/smt-nozzles",
    },
    background: "The customer resells and services pick-and-place lines across Brazil. Their end market runs a Japanese-built placement platform on boards carrying odd-form parts that standard tape feeders cannot present. Two gaps kept coming back in their service tickets: a belt feeder for a JM-series machine, and a gripper nozzle for parts that vacuum pickup cannot hold. The customer asked for both as engineered parts rather than catalogue items, which meant drawings, a component list and a build slot at our feeder partner.",
    challenge: "Odd-form parts do not arrive in tape. They sit in bulk, in tubes, or on reels with non-standard pitch. A standard feeder will not index them and a standard nozzle will not grip them. On top of that, the customer had to report progress to their own end customer in writing, every week, or lose the order to a local machine shop.",
    solution: "We treated the feeder as an engineered order. Jason Wu collected the odd-form component list and the machine interface on 19 Jan 2026, then routed the build to our feeder manufacturing partner. The frame, the belt path and the pickup position were built to the component list. For the nozzle we specified a gripper design (FA-32599 class, gripper body 2748) instead of a vacuum tip, so the part is held mechanically through the placement stroke.",
    implementation: "The feeder went from build confirmation on 14 Nov 2025 to an on-site run test on 17 Dec 2025, a 33-day window that included five written progress reports. The inspection was witnessed at the supplier site, followed by nameplate and dimensional checks, export documentation and a made-to-measure wooden case. The gripper nozzle followed in Jan 2026. The customer has since brought us custom radial and axial feeder work and a PCB magazine rack enquiry.",
    metrics: [
      { value: "33 days", label: "Build to inspection", basis: "Delivery record" },
      { value: "5 written cycles", label: "Progress reports issued", basis: "Delivery record" },
      { value: "2 (belt feeder, gripper nozzle)", label: "Engineered part programmes", basis: "Delivery record" },
      { value: "6+ over the period", label: "Product lines engaged", basis: "Delivery record" },
    ],
    benefits: [
      "A feeder built to the customer's own component list, not adapted from a catalogue part.",
      "Written weekly progress the distributor can forward to their end customer without rewriting it.",
      "Witnessed run test before shipment, so acceptance happens before the freight is paid.",
      "One supplier for the feeder, the nozzle and the spares that follow them.",
    ],
    timeline: [
      { date: "9 Jul 2025", event: "First enquiry recorded; end-customer background research started" },
      { date: "19 Jan 2026", event: "Odd-form component list and machine interface collected; feeder engineering opened" },
      { date: "14 Nov 2025", event: "Build confirmed with the feeder manufacturing partner; target delivery 24 Dec 2025" },
      { date: "21 Nov 2025", event: "Frame material preparation photos sent to the customer" },
      { date: "28 Nov - 12 Dec 2025", event: "Weekly written progress reports issued (3 cycles)" },
      { date: "17 Dec 2025", event: "On-site run test and pre-shipment inspection" },
      { date: "Dec 2025", event: "Nameplate, dimensional check, export documents, custom wooden export case" },
      { date: "31 Jan 2026", event: "Custom gripper nozzle specification released" },
      { date: "15 May 2026", event: "Second gripper nozzle programme opened; custom radial and axial feeder enquiry" },
    ],
    evidence: "Delivery record. Dates and milestones taken from the project system. No pricing, no customer identity.",
  },
  {
    id: "case-02",
    num: "02",
    title: "Multi-Category Distributor Programme: Taping, Counting, Cleaning and Insertion Spares",
    region: "Mexico",
    industry: "Equipment distribution / industrial electronics",
    status: "Delivered (multi-order)",
    statusTone: "done",
    recordedWindow: "Aug 2025 - May 2026",
    team: "Jason Wu",
    profile: "A Mexican distributor of SMT and wire-processing equipment serving industrial electronics manufacturers in the north of the country, with its own sales engineers and a service workshop.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/desc/2020/03/Semi-auto-SMD-reel-taping-machine.jpg?imageMogr2/thumbnail/960x640/format/webp",
      alt: "Semi-automatic SMD reel taping machine supplied to a Mexican equipment distributor",
      sourcePage: "https://www.smthelp.com/sjl80a-semi-auto-smd-reel-taping-machine-with-touch-screen.html",
    },
    background: "The relationship opened in Aug 2025 and widened quickly. Rather than a single machine sale, the distributor brings us whatever their end customers ask for: an SMD component counter, a forming and taping machine for vertical parts, pallet and fixture cleaners, a UV curing oven, terminal insertion machine spares, wire strippers and a terminal crimping machine. Our job is to turn each request into a technical package the distributor can resell under its own name.",
    challenge: "A distributor's problem is different from a factory's. They need the machine, the spec sheet, the sales collateral and the after-sales path before they will put their name on it. They also need field support: when an S7020-class terminal inserter at one of their customers threw an intermittent X-axis limit error, the distributor could not diagnose it alone.",
    solution: "We built the programme around three things. First, complete technical packages: 3D drawings, samples, catalogues, manuals and localised collateral per machine. Second, product training: we hosted the distributor's engineers in China for two weeks in Mar 2026, including a supplier visit. Third, remote fault support on installed machines, with spares picked, packed and dispatched from stock.",
    implementation: "Seven product lines moved through the programme in nine months. The forming and taping machine went from enquiry on 13 Mar 2026 to shipment on 6 May 2026, with a sample stage and a 3D drawing in between. The two-week training block in Mar 2026 put the distributor's own engineers in front of the machines and the supplier, so first-line support now sits in Mexico rather than in our inbox.",
    metrics: [
      { value: "7 in 9 months", label: "Product lines engaged", basis: "Delivery record" },
      { value: "14 days on site in China", label: "Distributor training", basis: "Delivery record" },
      { value: "54 days", label: "Enquiry to shipment (taping machine)", basis: "Delivery record" },
      { value: "Remote, resolved without a site visit", label: "Fault diagnosis", basis: "Delivery record" },
    ],
    benefits: [
      "Resell-ready packages: drawings, manuals, catalogues and localised collateral per machine.",
      "Two weeks of hands-on training for the distributor's engineers, including supplier access.",
      "Remote diagnosis and spares dispatch, so a line stop does not wait for a flight.",
      "A single point of contact across seven unrelated product categories.",
    ],
    timeline: [
      { date: "26 Aug 2025", event: "Distributor relationship opened" },
      { date: "6 Jan 2026", event: "Import clearance handled on the incoming side" },
      { date: "15 Jan 2026", event: "Export documentation prepared; pallet cleaner and UV curing oven enquiries opened" },
      { date: "19 Jan 2026", event: "Purchase order processed: PI, procurement, acceptance, packing, shipment, after-sales" },
      { date: "21 Jan 2026", event: "Shipment photographs issued" },
      { date: "4 Mar 2026", event: "SMD component counter order; wire stripping machine sampling for an end project" },
      { date: "8 - 21 Mar 2026", event: "Two-week distributor training programme hosted in China, with supplier visit" },
      { date: "13 Mar 2026", event: "Forming and taping machine: enquiry, 3D drawing, sample and final quotation" },
      { date: "16 Mar 2026", event: "Terminal insertion machine spares; intermittent X-axis limit error diagnosed remotely" },
      { date: "20 Apr 2026", event: "Purchase order received for the forming and taping machine" },
      { date: "6 May 2026", event: "Forming and taping machine shipped" },
      { date: "11 May 2026", event: "Terminal insertion machine spares shipped" },
      { date: "19 May 2026", event: "Automatic single-head terminal crimping machine enquiry opened" },
    ],
    evidence: "Delivery record. All dates from the project system. No pricing, no customer identity, no end-customer names.",
  },
  {
    id: "case-03",
    num: "03",
    title: "Feeder and Nozzle Co-Development with a Global Placement Machine Manufacturer",
    region: "Japan / United States / Mexico",
    industry: "SMT capital equipment manufacturing",
    status: "Delivered (framework agreement)",
    statusTone: "done",
    recordedWindow: "Oct 2020 - May 2026",
    team: "Jason Wu, Kevin Yang, Leon Hong",
    profile: "A multinational manufacturer of SMT pick-and-place machines, with a Japanese engineering headquarters and sales and service subsidiaries in the United States and Mexico.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/desc/2016/01/Samsung-stick-feeder-02.png?imageMogr2/thumbnail/960x640/format/webp",
      alt: "Vibration stick feeder of the class co-developed with a global placement machine manufacturer",
      sourcePage: "https://www.smthelp.com/product/viberation-stick-feeder-for-smt-samsung-pick-and-placemachine",
    },
    background: "This is a manufacturer-to-manufacturer relationship. Their machines ship worldwide; the feeders and nozzles that feed odd-form and terminal parts are the gap their own catalogue leaves open. We supply those as engineered parts: a reel terminal feeder for chain terminals, a vibration stick feeder for tube-fed parts, bulk feeders, tray feeders and custom nozzles. The work runs through three of their organisations at once, which is why three of our people are on it.",
    challenge: "Their engineering organisation does not accept a catalogue part number as an answer. Every design change has to be justified on the machine: pickup position, tube indexing, separation of parts in the tube. Documentation and CE marking are required before anything ships to a European or Japanese plant. And a quote that reaches their Mexican subsidiary has to match what their Japanese headquarters already approved.",
    solution: "We ran the feeders as a development programme rather than a spare-parts line. Two design revisions were made on the vibration stick feeder in Dec 2025: the tube separation and indexing method, and the pickup position. Nozzles were specified as gripper types where vacuum pickup fails. CE marking was completed in Dec 2025. Kevin Yang built the marketing and technical collateral for the Americas side; Leon Hong handled tray and belt feeder enquiries; Jason Wu carried the Japan and Mexico threads.",
    implementation: "The 10-unit batch ordered on 6 Jan 2026 was accepted on 19 Jan 2026, a 44-day turn including the redesign. CE marking was closed in Dec 2025, which removed the compliance question for European and Japanese deliveries. On 18 Mar 2026 the cooperation agreement with the Japanese headquarters was signed, turning a series of single orders into a standing framework.",
    metrics: [
      { value: "10 vibration stick feeders accepted 19 Jan 2026", label: "Batch acceptance", basis: "Delivery record" },
      { value: "2 (tube indexing, pickup position)", label: "Design revisions", basis: "Delivery record" },
      { value: "CE marking completed Dec 2025", label: "Certification", basis: "Delivery record" },
      { value: "44 days", label: "Enquiry to batch acceptance", basis: "Delivery record" },
      { value: "3 (Japan, United States, Mexico)", label: "Organisations covered", basis: "Delivery record" },
    ],
    benefits: [
      "Feeders engineered against their machine interface, with documented design revisions.",
      "CE marking in place before shipment, so no compliance hold at goods-in.",
      "One commercial and technical position across their Japan, US and Mexico organisations.",
      "Gripper nozzles for parts the standard vacuum tip cannot hold.",
    ],
    timeline: [
      { date: "31 Oct 2020", event: "Earliest record in the relationship" },
      { date: "29 Aug 2025", event: "Reel terminal feeder and custom nozzle enquiry" },
      { date: "30 Sep 2025", event: "Purchase order for the vibration stick feeder" },
      { date: "11 Nov 2025", event: "Belt reciprocating feeder development for a Mexico end market" },
      { date: "13 Dec 2025", event: "Nozzle rubber tip order processed" },
      { date: "15 Dec 2025", event: "PI issued and order confirmed with the customer" },
      { date: "17 Dec 2025", event: "Shipped, customer notified" },
      { date: "22 Dec 2025", event: "Vibration stick feeder redesign: tube separation, indexing and pickup position. CE marking completed" },
      { date: "6 Jan 2026", event: "Order for 10 vibration stick feeders" },
      { date: "19 Jan 2026", event: "Batch of 10 accepted" },
      { date: "27 Feb 2026", event: "Order for 2 feeders plus custom guide parts" },
      { date: "18 Mar 2026", event: "Cooperation agreement signed with the Japanese headquarters" },
      { date: "20 May 2026", event: "Custom nozzle and feeder enquiry via the Americas subsidiary" },
    ],
    evidence: "Delivery record. Dates from the project system. No pricing, no party names, no part numbers tied to contracts.",
  },
  {
    id: "case-04",
    num: "04",
    title: "Odd-Form Insertion Study for a Smart Bathroom Mirror Controller",
    region: "Canada",
    industry: "Building electronics / smart home controls",
    status: "Solution delivered",
    statusTone: "part",
    recordedWindow: "Jan 2026 - May 2026",
    team: "Jason Wu, Leon Hong",
    profile: "A North American building-electronics manufacturer developing controllers for smart bathroom mirrors, assembling in-house on a mixed SMT and through-hole line.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/shop_imgs/2025-3-11-17416781031720.jpg?imageMogr2/thumbnail/960x640/format/webp",
      alt: "Odd-form insertion machine of the class proposed for a smart mirror controller board",
      sourcePage: "https://www.smthelp.com/s7900-odd-form-insert-machine.html",
    },
    background: "The board carries nine component types that a standard radial or axial inserter will not handle in one pass: connectors, sockets and other irregular bodies in tape, tube and bulk packaging. The customer wanted to know whether a single odd-form platform could take all nine, and what that would do to their manual insertion headcount. Leon Hong led the board data collection; Jason Wu owned the proposal.",
    challenge: "Nine component types with three different packaging formats is where most odd-form projects stall. The board data has to be exact before any machine can be sized: board dimensions, thickness, back-side photograph, packaging per component, and whether the line runs one or two shifts. Without that, a proposal is a guess, and the customer's engineers would know it.",
    solution: "We collected the board specification first, then matched it against prior builds on the same platform. The proposal covered one odd-form platform with multiple heads and mixed feeding: chain-tab feeding for linked parts, bulk feeding for loose sockets, and tape feeding for the rest. We also produced a machine-specific demonstration video so the customer's team could see the feeding method before committing to a trial.",
    implementation: "The proposal was delivered 13 days after the enquiry, on 19 Jan 2026, following an internal review. The feeding configuration covers all three packaging formats on the board. The quantified figures above come from field records on this machine platform and on a comparable microwave oven control board built on the same platform; they are platform data, not measurements taken at this customer, whose own trial had not started at the time of writing.",
    metrics: [
      { value: "9", label: "Component types on the board", basis: "Specification" },
      { value: "3 (tape, tube, bulk)", label: "Packaging formats handled", basis: "Specification" },
      { value: "13 days", label: "Enquiry to final proposal", basis: "Delivery record" },
      { value: "50,000+ insertions, 0 defects, 100% insertion rate", label: "Field record on this platform", basis: "Measured" },
      { value: "8,000 pcs/hour, chain-tab plus taped Y-capacitor", label: "Field record, comparable board", basis: "Measured" },
    ],
    benefits: [
      "One platform for all nine component types instead of three separate feed mechanisms.",
      "Feeding method demonstrated on video before any trial commitment.",
      "Board-level data collection led by a named engineer, so the sizing is traceable.",
      "A published platform track record to check the proposal against.",
    ],
    timeline: [
      { date: "6 Jan 2026", event: "Enquiry received" },
      { date: "7 Jan 2026", event: "Background research, requirement analysis and technical feasibility assessment" },
      { date: "19 Jan 2026", event: "Solution draft, internal review meeting, revised and final proposal delivered" },
      { date: "20 Jan 2026", event: "Board application identified: smart bathroom mirror controller" },
      { date: "9 Feb 2026", event: "Machine-specific demonstration video produced" },
      { date: "12 May 2026", event: "Samples prepared" },
    ],
    evidence: "Delivery record plus platform field data. The 50,000-insertion and 8,000 pcs/h figures are field records on this machine platform and a comparable board, not measurements from this customer's line.",
  },
  {
    id: "case-05",
    num: "05",
    title: "Depanelizer Selection: Three Schemes Evaluated Before the Order",
    region: "India",
    industry: "Electronics manufacturing services",
    status: "Delivered",
    statusTone: "done",
    recordedWindow: "Aug 2025 - May 2026",
    team: "Jason Wu",
    profile: "An Indian electronics manufacturing services provider running several plants, with SMT assembly, depaneling and device programming under one roof.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/desc/2019/12/3D-pic-of-S-D3500S.png?imageMogr2/thumbnail/960x640/format/webp",
      alt: "Online routing PCB separator of the class supplied to an Indian EMS provider",
      sourcePage: "https://www.smthelp.com/s-d3500s-online-routing-pcb-separator-pcb-board-auto-cutting-machine.html",
    },
    background: "The customer already ran a guillotine-type V-cut separator and wanted to cut the number of passes per board. Their request came with a second requirement that shaped the whole project: after depaneling, the small boards have to be taped into reels for the next station. We started with a desktop router, ran the numbers, and ended somewhere else.",
    challenge: "A guillotine separator makes one straight cut per pass. A board that needs several cuts on different axes means several passes, an operator turning the board each time, and handling damage at the edges. The customer's stated objective was fewer cutting operations per board. The desktop router option was on the table first, but its throughput did not match their volume.",
    solution: "We put three schemes in front of them in Dec 2025 and let the board decide. Scheme one was a punch-type separator. Scheme two combined a groups-blade cutter with a traversing blade, working alongside their existing V-cut machine. Scheme three was a multi-blade groups-blade separator sized for the panel. Scheme three won. We also quoted six fixtures, ran samples, and built the proposal around their actual panel rather than a datasheet.",
    implementation: "The customer made their decision against three documented schemes rather than one recommendation, and the multi-blade configuration was the one that matched the panel. Inspection and operator training were completed on 23 Jan 2026, with the software manual localised before handover. Shipment documentation followed on 31 Mar 2026. The follow-on fixture enquiry in May 2026 suggests the machine is in production.",
    metrics: [
      { value: "3, compared side by side", label: "Schemes evaluated", basis: "Delivery record" },
      { value: "6", label: "Fixtures quoted", basis: "Delivery record" },
      { value: "17 months, including a factory visit", label: "Enquiry to inspection", basis: "Delivery record" },
      { value: "Operator training delivered 23 Jan 2026", label: "Training", basis: "Delivery record" },
      { value: "Software manual localised for the customer", label: "Documentation", basis: "Delivery record" },
    ],
    benefits: [
      "Three schemes compared on the customer's own panel, with the reasoning written down.",
      "Factory visit before the order, so the customer could see the build quality first-hand.",
      "Operator training and a localised manual at handover, not after a support ticket.",
      "Fixture supply carried forward as a repeat line.",
    ],
    timeline: [
      { date: "8 Aug 2025", event: "Depanelizer enquiry" },
      { date: "11 Aug 2025", event: "Background research" },
      { date: "4 Sep 2025", event: "Customer hosted for a factory visit" },
      { date: "5 Nov 2025", event: "Quotation issued" },
      { date: "11 - 13 Nov 2025", event: "Desktop router depanelizer scheme evaluated" },
      { date: "26 Nov 2025", event: "Six fixtures quoted" },
      { date: "3 Dec 2025", event: "Three schemes compared: punch type, groups-blade plus traversing blade, groups-blade independent" },
      { date: "20 Dec 2025", event: "Final multi-blade proposal issued; panel redesign option discussed" },
      { date: "23 Jan 2026", event: "Pre-shipment inspection and operator training; software manual localised" },
      { date: "31 Mar 2026", event: "Shipment documentation issued" },
      { date: "7 Apr 2026", event: "Payment confirmed" },
      { date: "15 May 2026", event: "New fixture enquiry, 125 pcs plus samples" },
    ],
    evidence: "Delivery record. Dates from the project system. Cut-count reduction is the design objective of the selected scheme, not a measured post-installation figure.",
  },
  {
    id: "case-06",
    num: "06",
    title: "Axial Insertion Machine Spares and a Rotary Table Drive Fault",
    region: "British Isles",
    industry: "Electronics manufacturing / EMS",
    status: "Delivered (repeat)",
    statusTone: "done",
    recordedWindow: "Dec 2019 - Jan 2026",
    team: "Sara Zhang, Jason Wu, Kevin Yang, Jack Chan",
    profile: "An electronics manufacturer in the British Isles running through-hole insertion lines, including horizontal (axial) machines, with its own mechanical and production engineering staff.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/desc/2015/11/45592425-FORMER-OUTSIDE-RH-scaled.jpg?imageMogr2/thumbnail/960x640/format/webp",
      alt: "Auto axial insertion machine spare part of the class supplied to a British Isles manufacturer",
      sourcePage: "https://www.smthelp.com/product/auto-axial-insertion-machine-spare-part",
    },
    background: "One of the longer relationships in our book, first recorded in Dec 2019 and still active in 2026. The customer runs Universal-class radial equipment and horizontal axial machines. Their engineering team sends part-numbered enquiries directly: distribution heads, forming frames, springs, control boards. They know what they need, which makes the job about sourcing accuracy and speed, not about selling.",
    challenge: "Two things go wrong on machines of this age. The mechanical spares wear on a predictable cycle, and the electronics fail without warning. In Dec 2025 the customer reported a rotary table motor drive fault on top of an open spares order. Without a working drive, the machine is down regardless of how many mechanical spares are in the box.",
    solution: "We handled the two tracks in parallel. The mechanical spares were quoted and supplied against their part numbers, in two consecutive orders raised six weeks apart. For the drive fault we worked from the symptom description rather than a part number, because the customer could not identify the failed board. Sara Zhang and Jason Wu carried the commercial side; Kevin Yang supported on the parts; Jack Chan's project carried the axial spares thread.",
    implementation: "Two spare-part orders were processed within six weeks of each other in late 2025, both quoted against the customer's own part numbers. The rotary table motor drive fault was diagnosed from symptom description in Dec 2025, without a site visit. A long-term cooperation plan covering the spares range was drafted on 27 Dec 2025.",
    metrics: [
      { value: "6 years, first recorded Dec 2019", label: "Relationship length", basis: "Delivery record" },
      { value: "2, raised 6 weeks apart", label: "Consecutive orders", basis: "Delivery record" },
      { value: "Rotary table motor drive, Dec 2025", label: "Fault diagnosis", basis: "Delivery record" },
      { value: "4 (Sarah Zhang, Jason Wu, Kevin Yang, Jack Chan projects)", label: "Sales channels", basis: "Delivery record" },
    ],
    benefits: [
      "Part-numbered enquiries answered with sourced equivalents, not substitutes.",
      "Fault diagnosis from a symptom description, avoiding a site visit.",
      "Six years of history on this machine range, so part identification is fast.",
      "Four people across the account, so cover does not depend on one inbox.",
    ],
    timeline: [
      { date: "9 Dec 2019", event: "First record in the relationship" },
      { date: "21 Nov 2025", event: "Background research; spare parts requirement captured" },
      { date: "24 Nov 2025", event: "Horizontal axial machine spares quoted against a purchase order raised 6 Oct 2025" },
      { date: "1 Dec 2025", event: "Second spare parts order quoted" },
      { date: "8 Dec 2025", event: "Rotary table motor drive fault reported and diagnosed" },
      { date: "27 Dec 2025", event: "Long-term cooperation plan, spares market review and sales strategy drafted" },
      { date: "9 Jan 2026", event: "Relationship review" },
    ],
    evidence: "Delivery record. Dates from the project system. No pricing, no customer identity, no part numbers published.",
  },
  {
    id: "case-07",
    num: "07",
    title: "Reel and Bulk Terminal Feeder Programme for an Insertion Line",
    region: "Brazil",
    industry: "Electronics manufacturing / insertion assembly",
    status: "Engineering stage",
    statusTone: "open",
    recordedWindow: "May 2021 - Feb 2026",
    team: "Jimmy Zheng, Jason Wu, Kevin Yang, Leon Hong, Marie",
    profile: "A Brazilian manufacturer running axial and radial through-hole insertion equipment, buying insertion machine spares and peripheral equipment for its own lines.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/ueditor/php/upload/image/20230503/1683084867630726.png?imageMogr2/thumbnail/960x640/format/webp",
      alt: "Terminal insertion machine of the class the reel and bulk terminal feeders were engineered for",
      sourcePage: "https://www.smthelp.com/s7020-series-pin-eyelet-terminal-insertion-machine.html",
    },
    background: "This account goes back to 2021, when insertion machines were first sold into Brazil through us. The volume has never been large and the orders have been spread across several years and five of our people. In 2026 the conversation restarted around terminal feeding: chain terminals on reels, and loose terminals fed from bulk.",
    challenge: "Terminal feeding fails in two specific ways. On a reel, the carrier strip has to index accurately or the terminal arrives at the insertion head out of position. In bulk, loose terminals have to be singulated and oriented without jamming. Both have to fit the customer's existing insertion platform, which is the part nobody can verify from a datasheet.",
    solution: "We started with compatibility, not with a quotation. In Feb 2026 we ran requirement analysis, device compatibility verification and technical evaluation before any price was discussed. In parallel we produced the sales material the customer's purchasing team needs to justify the buy: a product landing page, 3D renders of the reel terminal feeder, and a separate 3D and selling-point package for the bulk terminal feeder.",
    implementation: "The programme reached the quotation stage on 11 Feb 2026 with compatibility verified against the customer's existing insertion platform. Two feeding modes were engineered: reel-fed chain terminals and bulk-fed loose terminals. Because the machine itself has not been installed, the outcome figures here are engineering and delivery facts, not production measurements.",
    metrics: [
      { value: "2 (reel terminal, bulk terminal)", label: "Feeding modes engineered", basis: "Specification" },
      { value: "Verified against the existing insertion platform", label: "Compatibility checks", basis: "Delivery record" },
      { value: "3 (landing page, 2 x 3D packages)", label: "Sales assets produced", basis: "Delivery record" },
      { value: "5 across the period", label: "People on the account", basis: "Delivery record" },
    ],
    benefits: [
      "Compatibility checked against the existing platform before any price is discussed.",
      "Two feeding modes covered: reel-fed chain terminals and bulk loose terminals.",
      "3D models and a landing page the customer can circulate internally to get approval.",
      "Account history going back to 2021, so we know which machine range we are feeding.",
    ],
    timeline: [
      { date: "9 May 2021", event: "Earliest record; insertion machines first sold into Brazil" },
      { date: "19 Jan 2026", event: "Account history reviewed ahead of re-engagement" },
      { date: "20 Jan 2026", event: "Product landing page and 3D renders produced" },
      { date: "23 Jan 2026", event: "Bulk terminal feeder: 3D model and selling-point package produced" },
      { date: "26 - 27 Jan 2026", event: "Background research and pain-point analysis" },
      { date: "11 Feb 2026", event: "Terminal feeder enquiry; requirement analysis, compatibility verification, technical evaluation and quotation prepared" },
    ],
    evidence: "Engineering and commercial record. No production measurements exist for this account; the machine has not been installed.",
  },
  {
    id: "case-08",
    num: "08",
    title: "Mixed Axial and Radial Insertion Configuration for Lighting Control Gear",
    region: "Serbia",
    industry: "Lighting control gear / LED drivers",
    status: "Quotation stage",
    statusTone: "open",
    recordedWindow: "Jan 2026 - Apr 2026",
    team: "Jason Wu, Kevin Yang",
    profile: "A European manufacturer of lighting control gear, producing LED drivers and ballasts on boards up to 400 x 250 mm with a mixed axial and radial component population.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/desc/2015/11/Carrier-Clips.003.jpg?imageMogr2/thumbnail/960x640/format/webp",
      alt: "Carrier clips for radial insertion machines, supplied as consumables alongside the machine configuration",
      sourcePage: "https://www.smthelp.com/product/carrier-clip-for-uic-radial-insertion-machine",
    },
    background: "Enquiry received Jan 2026 for insertion capacity on LED driver and ballast boards. The board format was the binding constraint: up to 400 x 250 mm, with both axial and radial components on the same assembly. The customer also runs UIC-class radial equipment, which brought a consumables requirement with it.",
    challenge: "A 400 x 250 mm board is large for an insertion machine, and mixing axial and radial parts on it means either two machines or a machine with both heads. Alongside the capital question sits a consumables one: radial carrier clips wear continuously, and if they are not stocked the machine stops for a part that costs very little.",
    solution: "We quoted a combined axial and radial configuration sized for the 400 x 250 mm board, and registered as an approved supplier in parallel so the consumables can follow. The radial carrier clip requirement was quoted separately as a stocked consumable. Kevin Yang handled the background research; Jason Wu built the configuration and the two machine landing pages used as technical collateral.",
    implementation: "Supplier registration and the combined axial and radial quotation were both completed on 27 Jan 2026, two days after the enquiry. The configuration is sized for the customer's 400 x 250 mm maximum board. The carrier clip requirement was quoted separately on 2 Feb 2026 as a stocked consumable. The capital order had not been placed at the time of writing.",
    metrics: [
      { value: "400 x 250 mm", label: "Maximum board size", basis: "Specification" },
      { value: "2 (axial and radial)", label: "Insertion technologies", basis: "Specification" },
      { value: "Completed 27 Jan 2026", label: "Supplier registration", basis: "Delivery record" },
      { value: "2 days", label: "Enquiry to quotation", basis: "Delivery record" },
    ],
    benefits: [
      "One configuration covering both axial and radial parts on the same board.",
      "Sized to the customer's stated maximum board, 400 x 250 mm.",
      "Consumables quoted as a stocked line so wear parts do not stop the machine.",
      "Approved-supplier status completed before the first order, not after.",
    ],
    timeline: [
      { date: "25 Jan 2026", event: "Enquiry received" },
      { date: "26 Jan 2026", event: "Background research; axial and radial machine landing pages produced" },
      { date: "27 Jan 2026", event: "Supplier registration completed; axial plus radial quotation issued" },
      { date: "2 Feb 2026", event: "Radial insertion machine spare parts, including carrier clips, quoted" },
      { date: "17 Apr 2026", event: "Axial and radial insertion machine enquiry followed up" },
    ],
    evidence: "Quotation and supplier registration record. Board size is the customer's stated maximum. No production measurements exist; no machine has been installed.",
  },
  {
    id: "case-09",
    num: "09",
    title: "AGV Pallet Return Loop and Odd-Form Insertion for a Global Lighting Manufacturer",
    region: "Mexico / India",
    industry: "LED lighting manufacturing",
    status: "Delivered (with 2026 support)",
    statusTone: "done",
    recordedWindow: "Mar 2020 - Jan 2026",
    team: "Shaoyong, Jason Wu, Kevin Yang, Albert, Lucy, Ronin, Wendy Yu",
    profile: "A multinational lighting manufacturer operating high-volume LED luminaire plants in Mexico and India, running wave soldering with pallets and mixed-technology assembly lines.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/desc/2022/08/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_202208181110524.png?imageMogr2/thumbnail/960x640/format/webp",
      alt: "AGV of the class used to return wave soldering pallets in a lighting plant",
      sourcePage: "https://www.smthelp.com/agv-robot-for-moving-pcbs-in-factory.html",
    },
    background: "The earliest order on this account predates the current project system; a 2017 order reference sits in the history. The plants run wave soldering with pallets, and those pallets have to come back to the line start. Moving them by hand is a material-handling job that scales badly with volume. We supplied AGVs for the return loop and, separately, worked an odd-form insertion requirement at the Indian plant.",
    challenge: "Two problems, one operational and one administrative. Operationally, pallet return is a loop: if the pallets do not come back, the wave solder machine waits. Administratively, when the customer wanted to import additional AGVs in 2026, their customs broker needed documentation on the earlier shipment, and the original commercial terms were not in the customer's hands.",
    solution: "For the operational side we supplied AGVs sized for pallet return and built the case material around the loop rather than the vehicle. For the administrative side Jason Wu re-opened the 2026 thread on 16 Jan 2026, retrieved the original shipment documentation and supported the customer's import. Shaoyong has carried the account across most of its projects; Kevin Yang, Albert, Lucy, Ronin and Wendy Yu have each handled threads on it.",
    implementation: "AGVs were delivered into the Mexican plant for wave soldering pallet return. In Jan 2026 the customer came back needing import documentation for a repeat shipment, which we retrieved and supplied. The account spans eight projects and seven of our people across two countries, and the odd-form insertion thread at the Indian plant remains open.",
    metrics: [
      { value: "2 countries (Mexico, India)", label: "Plants covered", basis: "Delivery record" },
      { value: "8", label: "Projects on the account", basis: "Delivery record" },
      { value: "7", label: "People on the account", basis: "Delivery record" },
      { value: "6 years in the current system, plus a 2017 order", label: "Relationship length", basis: "Delivery record" },
    ],
    benefits: [
      "Pallet return automated, so the wave solder machine is not waiting on a manual loop.",
      "Import documentation retrieved years later, when customs asked for it.",
      "One case study covering both the AGV loop and the odd-form insertion requirement.",
      "Seven people across the account, so knowledge is not held by one contact.",
    ],
    timeline: [
      { date: "13 Apr 2017", event: "Earlier order reference held in the account history" },
      { date: "11 Mar 2020", event: "Earliest record in the current project system" },
      { date: "(prior year)", event: "AGVs shipped for pallet return; carrier tracking referenced by the customer in 2026" },
      { date: "16 Jan 2026", event: "AGV after-sales support: import documentation for the earlier shipment" },
      { date: "16 Jan 2026", event: "Case study compiled on the odd-form insertion and AGV solution" },
      { date: "16 Jan 2026", event: "AGV product knowledge base built for the sales team" },
    ],
    evidence: "Delivery and support record. Dates from the project system. No pricing, no customer identity, no shipment values.",
  },
  {
    id: "case-10",
    num: "10",
    title: "Stencil Cleaner Consumables and Spares for a Maquiladora SMT Line",
    region: "Mexico",
    industry: "Electronic components manufacturing",
    status: "Commercial stage",
    statusTone: "open",
    recordedWindow: "Jan 2026",
    team: "Jason Wu, Kevin Yang",
    profile: "The Mexican plant of a multinational electronic components manufacturer, operating SMT lines in a maquiladora environment with a combined maintenance and process engineering function.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/shop_imgs/2023-3-21-16794092140161.png?imageMogr2/thumbnail/960x640/format/webp",
      alt: "SMT stencil cleaning machine of the class the spares and consumables were quoted for",
      sourcePage: "https://www.smthelp.com/s1688-smt-stencil-cleaning-machine.html",
    },
    background: "Enquiry received 6 Jan 2026 for spares on a stencil cleaning machine. The person who raised it holds both maintenance supervision and SMT process engineering responsibilities, which changes how the approach has to be framed: the maintenance side cares about uptime and consumables, the process side about cleaning results and IPC compliance.",
    challenge: "A combined maintenance and process role means one conversation has to answer two sets of questions. On top of that, this is a plant inside a multinational group, so anything bought locally has to survive a purchasing review that sits outside Mexico. Generic English collateral does not help an engineer whose first language is Spanish and whose buyer is somewhere else.",
    solution: "We split the work by discipline. Kevin Yang mapped the contact's role, the plant's scale and the existing cleaner model. Jason Wu built the technical package around the pneumatic safety and filtration systems, and produced a Spanish-language demonstration video rather than an English PDF. Three differentiated commercial options were prepared: a spares kit, an annual maintenance arrangement, and a trade-in. A technical file was opened to record serial numbers and service history.",
    implementation: "The first technical contact was made one day after the enquiry, on 7 Jan 2026, with a Spanish-language demonstration video rather than a catalogue. By 8 Jan 2026 the existing machine model was confirmed, the spares list and technical parameters were compiled, and three commercial options were on the table. The order had not been placed at the time of writing.",
    metrics: [
      { value: "3 (spares kit, annual maintenance, trade-in)", label: "Commercial options", basis: "Delivery record" },
      { value: "1 day", label: "Enquiry to first technical contact", basis: "Delivery record" },
      { value: "Spanish demonstration video produced", label: "Language localisation", basis: "Delivery record" },
      { value: "2 (maintenance, SMT process)", label: "Disciplines covered", basis: "Delivery record" },
    ],
    benefits: [
      "Technical material in the plant's working language, not English-only PDFs.",
      "Three commercial structures, so the buyer can pick the one that fits their budget cycle.",
      "Pneumatic safety and filtration covered explicitly, which is what maintenance asks about.",
      "A technical file opened from day one, so serial numbers and service history are recorded.",
    ],
    timeline: [
      { date: "6 Jan 2026", event: "Enquiry received" },
      { date: "7 Jan 2026", event: "Spanish-language demonstration video produced; first technical contact made" },
      { date: "7 Jan 2026", event: "Three commercial options prepared; technical file opened; local service follow-up" },
      { date: "8 Jan 2026", event: "Contact's role analysed; plant scale and purchasing process researched" },
      { date: "8 Jan 2026", event: "Existing cleaner model confirmed; spares list and technical parameters compiled" },
    ],
    evidence: "Commercial record. Dates from the project system. No pricing, no customer identity. No production measurements exist at this stage.",
  },
  {
    id: "case-11",
    num: "11",
    title: "ESD Board Handling Racks Qualified Against 80 degrees C",
    region: "United States",
    industry: "LED device manufacturing / in-house PCBA",
    status: "Delivered",
    statusTone: "done",
    recordedWindow: "Aug 2025 - Jan 2026",
    team: "Kevin Yang, Jason Wu, Leo Liao",
    profile: "A US manufacturer of LED-based personal care devices, assembling its own control boards in-house on a compact SMT line.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/shop_imgs/2025-1-7-17362205404700.png?imageMogr2/thumbnail/960x640/format/webp",
      alt: "ESD PCB turnover rack of the class supplied in a 250-unit order",
      sourcePage: "https://www.smthelp.com/esd-pcb-turnover-rack.html",
    },
    background: "The customer was using an imported board stand and wanted an ESD-safe rack for moving populated boards between stations. Two requirements came with the enquiry: the rack has to hold boards without flexing them, and it has to survive contact with boards that have not fully cooled. The order was for 250 units.",
    challenge: "The thermal question is the one that gets missed. A board coming off reflow or wave soldering is still hot when it lands in a rack. A rack specified only for room-temperature handling will deform, and once it deforms it stops protecting the boards. The customer asked for a written confirmation of the temperature limit before ordering, not after.",
    solution: "We confirmed the continuous temperature rating at 80 degrees C before the quotation was accepted, and put it in writing. The rack geometry was specified to support boards by their edges, keeping populated faces clear. Once the ESD order was in, the customer extended the relationship to spares for their Japanese placement platform, which we quoted on a separate PI.",
    implementation: "The 250-unit order was quoted, procured, inspected and shipped inside Nov 2025. The 80 degrees C rating was confirmed in writing before the order, which is what the customer asked for. The account extended into spares for their Japanese placement platform on 1 Dec 2025.",
    metrics: [
      { value: "250 racks", label: "Units shipped", basis: "Delivery record" },
      { value: "80 degrees C continuous, confirmed in writing", label: "Temperature rating", basis: "Specification" },
      { value: "Same month, Nov 2025", label: "Enquiry to shipment", basis: "Delivery record" },
      { value: "2 (ESD handling, placement machine spares)", label: "Product lines", basis: "Delivery record" },
    ],
    benefits: [
      "A written temperature rating, so the rack is not the weak link after reflow.",
      "Edge-supported board handling, keeping populated faces clear of contact.",
      "A drop-in replacement for the imported board stand the customer was using.",
      "One supplier for board handling and placement machine spares.",
    ],
    timeline: [
      { date: "14 Aug 2025", event: "Earliest record on the account" },
      { date: "22 Nov 2025", event: "ESD board rack enquiry; PI issued; procurement, acceptance and shipment arranged" },
      { date: "22 Nov 2025", event: "Background research and long-term cooperation plan drafted" },
      { date: "25 Nov 2025", event: "Account plan reviewed by a second sales engineer" },
      { date: "1 Dec 2025", event: "spares for their Japanese placement platform quoted on a separate PI" },
      { date: "6 Jan 2026", event: "Account updated" },
    ],
    evidence: "Delivery record. Dates and quantities from the project system. Temperature rating is the product specification confirmed to the customer.",
  },
  {
    id: "case-12",
    num: "12",
    title: "BGA Rework Station Heater Cores: 18 Days From Enquiry to Shipment",
    region: "United States",
    industry: "Electronics service and rework",
    status: "Delivered",
    statusTone: "done",
    recordedWindow: "Jan 2026",
    team: "Jason Wu",
    profile: "A US industrial electronics service provider operating BGA rework stations, buying replacement heater assemblies as consumable service parts.",
    image: null,
    background: "An existing customer with a prior order history, so no onboarding was needed. On 10 Jan 2026 they asked for replacement heater cores for a BGA rework station, specified by the heater part code. Twelve units were required. The whole exchange ran inside three weeks.",
    challenge: "A heater core is a service part, and a rework station without one is a bench out of action. The customer's exposure is downtime, not part cost. The sourcing problem is that heater assemblies are often treated as machine-specific spare parts with long lead times, so the usual outcome is a three or four week wait from the original equipment maker.",
    solution: "We treated it as a fast-turn consumable order rather than a capital spares request. The customer's part code was matched against our supplier on 21 Jan 2026, the goods were received from the supplier on 28 Jan 2026, and the forwarder was booked the same day. Commercial paperwork, the PI and the commercial invoice, was produced in step with the goods rather than after them.",
    implementation: "Twelve heater cores went from enquiry on 10 Jan 2026 to shipment on 28 Jan 2026, eighteen days in total. Once payment was received on 21 Jan 2026, the order was placed the same day and the goods were received and dispatched on 28 Jan 2026, eight days later.",
    metrics: [
      { value: "12 heater cores", label: "Units shipped", basis: "Delivery record" },
      { value: "18 days", label: "Enquiry to shipment", basis: "Delivery record" },
      { value: "8 days", label: "Payment to dispatch", basis: "Delivery record" },
      { value: "Same day, 28 Jan 2026", label: "Supplier to dispatch", basis: "Delivery record" },
    ],
    benefits: [
      "Eighteen days from first enquiry to shipment on a service-critical part.",
      "Forwarder booked the same day the goods arrived from the supplier.",
      "Part code matched against an existing supply channel rather than the original equipment maker.",
      "Commercial paperwork produced in step with the goods, so nothing waits on documents.",
    ],
    timeline: [
      { date: "7 Jan 2026", event: "Account review; existing order history confirmed" },
      { date: "10 Jan 2026", event: "BGA rework station spare parts enquiry" },
      { date: "12 Jan 2026", event: "Quotation drafted; quotation email prepared" },
      { date: "14 Jan 2026", event: "Purchase order received for 12 heater cores" },
      { date: "16 Jan 2026", event: "Quotation issued" },
      { date: "20 Jan 2026", event: "Purchase order confirmed; PI issued" },
      { date: "21 Jan 2026", event: "Payment received; order placed with the supplier" },
      { date: "28 Jan 2026", event: "Goods received from supplier; forwarder booked; commercial invoice issued and shipped" },
    ],
    evidence: "Delivery record. Dates and quantities from the project system. No pricing, no customer identity, no supplier terms.",
  },
  {
    id: "case-13",
    num: "13",
    title: "Repeat Insertion Machine Spares, Wave Soldering Parts and Feeders",
    region: "Turkey",
    industry: "Electronic measuring instruments",
    status: "Delivered (repeat)",
    statusTone: "done",
    recordedWindow: "Sep 2025 - May 2026",
    team: "Leon Hong",
    profile: "A Turkish manufacturer of electronic measuring instruments, running through-hole insertion equipment, wave soldering and placement machines, with a purchasing team that buys spares in recurring batches.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/desc/2019/03/47152202-finger-7-scaled.jpg?imageMogr2/thumbnail/960x640/format/webp",
      alt: "Insertion machine spare part of the class supplied in repeat orders to a Turkish instrument manufacturer",
      sourcePage: "https://www.smthelp.com/product/47152202-finger-universal-instruments-ai-spare-parts-panasonic-ai-spare-parts",
    },
    background: "Leon Hong's account, opened Sep 2025 and settled into a repeat rhythm within two months. The pattern is a spare-part batch, then a stocking cycle, then a shipment, then the next batch. In 2026 the range widened from insertion machine spares into wave soldering parts and placement machine feeders.",
    challenge: "Spare-part buying on this kind of account fails in a specific way: the enquiry comes in, a quote goes out, and the order stalls because nobody has sat down together to check what is actually in stock and what is actually needed. The 2026 batch was heading the same way until the supplier and the customer were put in the same meeting.",
    solution: "For the first batches we ran the standard cycle: background research, payment PI, stocking, certificate of origin, shipment, then the next order. For the 2026 batch Leon Hong changed the approach and convened a joint meeting with the supplier and the customer to review stock and push the order forward. That converted an open enquiry into an order in eleven days.",
    implementation: "Two spare-part batches were completed in 2025, the second ordered before the first had finished shipping. The 2026 batch ran from enquiry on 8 Apr 2026 to shipment documentation on 13 May 2026, thirty-five days, with a joint supplier and customer meeting on 20 Apr 2026 that turned the enquiry into an order eleven days later.",
    metrics: [
      { value: "2 completed in 2025, 1 in 2026", label: "Repeat batches", basis: "Delivery record" },
      { value: "35 days (8 Apr to 13 May 2026)", label: "2026 enquiry to shipment", basis: "Delivery record" },
      { value: "11 days", label: "Enquiry to order after joint meeting", basis: "Delivery record" },
      { value: "3 (insertion spares, wave soldering parts, feeders)", label: "Product range", basis: "Delivery record" },
    ],
    benefits: [
      "A joint supplier and customer meeting, which is what unlocked the 2026 order.",
      "Range widened from insertion spares to wave soldering parts and feeders.",
      "Items can be added to an open order, as the pneumatic spray part was on 13 May 2026.",
      "Certificate of origin and shipping photographs provided as standard.",
    ],
    timeline: [
      { date: "29 Sep 2025", event: "Account background captured" },
      { date: "7 Oct 2025", event: "Payment PI issued" },
      { date: "9 Oct 2025", event: "Stocking" },
      { date: "15 Oct 2025", event: "Certificate of origin" },
      { date: "30 Oct 2025", event: "Shipment" },
      { date: "7 Nov 2025", event: "Second insertion machine spares order; quotation, payment proof and PI" },
      { date: "14 Nov 2025", event: "Shipping documentation" },
      { date: "14 Dec 2025", event: "Stocking" },
      { date: "8 Apr 2026", event: "Wave soldering machine spares enquiry" },
      { date: "20 Apr 2026", event: "Placement machine feeder enquiry; joint supplier and customer meeting held" },
      { date: "21 Apr 2026", event: "Order placed" },
      { date: "27 Apr 2026", event: "Quotation and PI issued" },
      { date: "5 May 2026", event: "Balance PI issued" },
      { date: "13 May 2026", event: "Shipping documentation and photographs; pneumatic spray part added to the order" },
    ],
    evidence: "Delivery record. Dates from the project system. No pricing, no customer identity.",
  },
  {
    id: "case-14",
    num: "14",
    title: "SMT Splice Clips: Eight Days From Enquiry to Dispatch",
    region: "Ecuador",
    industry: "Home appliance manufacturing / in-house SMT",
    status: "Delivered",
    statusTone: "done",
    recordedWindow: "Jan 2026 - Feb 2026",
    team: "Jason Wu, Kevin Yang",
    profile: "A home appliance manufacturer in Ecuador operating its own SMT lines, buying SMT consumables and factory supplies in small recurring orders.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/desc/2016/01/SMT-tape-splicing-table-02.png?imageMogr2/thumbnail/960x640/format/webp",
      alt: "SMT splicing tool and brass splice clips of the class shipped to an Ecuadorian appliance manufacturer",
      sourcePage: "https://www.smthelp.com/product/smt-splicing-tool-embossed-feeder-tape-brass-stitch-and-tape-splice",
    },
    background: "A small consumables order with a long history behind it. The account appears in our records under an earlier company name dating back to 2018, when it bought SMT factory supplies. In Jan 2026 it came back under its current name for splice clips, the brass clips used to join carrier tape so a feeder does not run empty during a changeover.",
    challenge: "Small consumables orders are disproportionately expensive to get wrong. The unit value does not justify a long administrative cycle, but the part stops a line when it is missing. The freight and the commercial invoice have to be right the first time, because a small shipment held at customs costs more than the goods.",
    solution: "We compressed the cycle. Background research and product study ran on 30 Jan 2026. The PI, photographic confirmation of the goods, the commercial invoice and the freight were all handled on 3 Feb 2026. Stocking, dispatch and the tracking number followed on 5 Feb 2026. When a delivery problem surfaced on 13 Feb 2026, Jason Wu took it directly rather than routing it through a ticket.",
    implementation: "Splice clips went from background research on 30 Jan 2026 to dispatch with a tracking number on 5 Feb 2026. Commercial paperwork, goods photography and freight were handled in a single working session on 3 Feb 2026. A delivery issue surfaced on 13 Feb 2026 and was closed the same week.",
    metrics: [
      { value: "6 days (30 Jan to 5 Feb 2026)", label: "Research to dispatch", basis: "Delivery record" },
      { value: "14 days including delivery issue", label: "Enquiry to closure", basis: "Delivery record" },
      { value: "PI, photographic confirmation, commercial invoice, freight, tracking", label: "Documentation", basis: "Delivery record" },
      { value: "Prior orders under a previous company name", label: "Account history", basis: "Delivery record" },
    ],
    benefits: [
      "Six days from research to dispatch on a consumable line.",
      "Photographic confirmation of the goods before they leave, so there is no dispute about what was sent.",
      "Tracking number issued with the dispatch, not on request.",
      "Delivery problems handled directly by the account owner.",
    ],
    timeline: [
      { date: "(prior years)", event: "Earlier orders recorded under the account's previous company name" },
      { date: "30 Jan 2026", event: "Background research and product study" },
      { date: "3 Feb 2026", event: "PI issued; goods confirmed by photograph; commercial invoice and freight arranged" },
      { date: "5 Feb 2026", event: "Order processed: splice clips stocked, dispatched, tracking number issued" },
      { date: "13 Feb 2026", event: "Delivery issue raised and resolved" },
    ],
    evidence: "Delivery record. Dates from the project system. No pricing, no customer identity, no quantities published.",
  },
  {
    id: "case-15",
    num: "15",
    title: "Wave Soldering Consumables Consolidated With ESD and Cleanroom Sourcing",
    region: "Argentina",
    industry: "Industrial electronics distribution",
    status: "Sourcing stage",
    statusTone: "open",
    recordedWindow: "Nov 2025 - Mar 2026",
    team: "Jason Wu",
    profile: "An Argentine distributor and service partner supplying industrial electronics manufacturers, acting as the buying channel for several local plants rather than for one factory.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/desc/2019/08/wave-finger6.jpg?imageMogr2/thumbnail/960x640/format/webp",
      alt: "Wave soldering fingers and titanium claws of the class quoted to an Argentine distributor",
      sourcePage: "https://www.smthelp.com/product/smt-wave-soldering-fingers-wave-soldering-double-hook-titanium-claws",
    },
    background: "The account opened Nov 2025. In Mar 2026 the distributor came in with a wave soldering consumables requirement, titanium fingers and flux spray nozzles, for a named end user. The conversation did not stop there: within five days it had expanded into ESD products, a modular cleanroom and an environmental chamber.",
    challenge: "A distributor serving several plants ends up with a scattered requirement: soldering consumables here, ESD there, a cleanroom somewhere else. Handled separately, that is three sourcing exercises, three freight arrangements and three sets of paperwork for one customer relationship. It is also how orders get lost.",
    solution: "We consolidated. The wave soldering consumables were quoted first because they were the live requirement. The ESD, modular cleanroom and environmental chamber items were then sourced as a single programme, using AI-assisted supplier screening against a Chinese wholesale platform to shortlist candidates before any quotation went out. The end user's details were captured up front so the specification could be checked at the plant level, not at the distributor level.",
    implementation: "Four requirement categories were brought into one sourcing programme within six days in Mar 2026. The end user was identified on day one so the wave soldering specification could be checked against the actual machine. Supplier screening was completed for the cleanroom, chamber and ESD flooring items. No order had been placed at the time of writing.",
    metrics: [
      { value: "4 (wave soldering, ESD, cleanroom, chamber)", label: "Requirement categories", basis: "Delivery record" },
      { value: "5 days from first to third category", label: "Category expansion", basis: "Delivery record" },
      { value: "AI-assisted shortlisting before quotation", label: "Sourcing method", basis: "Delivery record" },
      { value: "Identified before specification", label: "End user", basis: "Delivery record" },
    ],
    benefits: [
      "Four categories handled as one programme, one freight arrangement, one set of paperwork.",
      "End user identified up front, so specifications are checked at the plant.",
      "Suppliers shortlisted before any quotation goes out, not after.",
      "Wave soldering consumables and ESD bought from the same place.",
    ],
    timeline: [
      { date: "5 Nov 2025", event: "Account opened" },
      { date: "12 Mar 2026", event: "Background research; wave soldering spares enquiry: titanium fingers and flux spray nozzles" },
      { date: "12 Mar 2026", event: "End user identified and recorded for specification checking" },
      { date: "17 Mar 2026", event: "ESD products enquiry; modular cleanroom supplier screening started" },
      { date: "17 Mar 2026", event: "Walk-in environmental chamber supplier screening started" },
      { date: "18 Mar 2026", event: "ESD interlocking flooring supplier screening started" },
    ],
    evidence: "Sourcing record. Dates from the project system. No pricing, no customer identity, no end-user name published.",
  },
  {
    id: "case-16",
    num: "16",
    title: "Auto-Insertion Line Spares Across Six Machine Categories",
    region: "Turkey",
    industry: "PCB assembly / through-hole insertion",
    status: "Delivered (repeat)",
    statusTone: "done",
    recordedWindow: "Nov 2025 - May 2026",
    team: "Leon Hong, Wayne Guo",
    profile: "A Turkish PCB assembler running a mixed through-hole insertion line, including an existing horizontal inserter, and buying spares across insertion, placement, wave soldering and forming equipment.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/desc/2020/12/1.jpg?imageMogr2/thumbnail/960x640/format/webp",
      alt: "Axial auto insertion machine of the class the spare parts programme supports",
      sourcePage: "https://www.smthelp.com/s4000-axial-auto-insertion-machine.html",
    },
    background: "The account carries an AI insertion machine line requirement, axial and radial, alongside an existing horizontal inserter already on the floor. What actually converted into orders was the spares side. Four batches ran between Nov 2025 and May 2026, across six machine categories, handled by two of our people.",
    challenge: "Spare-part coverage on a mixed insertion line is a range problem. One order covered vertical and horizontal inserter parts, placement machine parts, wave soldering parts, forming machine parts and nozzle gripper pads. Sourcing that breadth from a single supplier is unusual; most assemblers end up with four or five vendors and four or five sets of paperwork.",
    solution: "We ran it as a rolling spares programme rather than as discrete orders. The first batch was quoted in Dec 2025, stocked and shipped in Jan 2026, and extended the same month with feeder sliders and solenoid valves. The second and third batches followed the same pattern. Each batch consolidated parts for several machine types into one shipment.",
    implementation: "Four spare-part batches ran between Nov 2025 and May 2026. The 6 Feb 2026 batch alone covered vertical and horizontal inserter spares, placement machine parts, wave soldering parts, forming machine parts and nozzle gripper pads. Coverage was extended on 28 Jan 2026 with feeder sliders and solenoid valves.",
    metrics: [
      { value: "4 between Nov 2025 and May 2026", label: "Spare-part batches", basis: "Delivery record" },
      { value: "Up to 6", label: "Machine categories per batch", basis: "Delivery record" },
      { value: "Feeder sliders and solenoid valves added 28 Jan 2026", label: "Range extension", basis: "Delivery record" },
      { value: "2", label: "People on the account", basis: "Delivery record" },
    ],
    benefits: [
      "Six machine categories sourced from one supplier, on one shipment.",
      "Parts can be added to a batch before it ships, as the solenoid valves were.",
      "Two people on the account, so cover is not dependent on one contact.",
      "Spares coverage extends to the placement and wave soldering machines, not just the inserters.",
    ],
    timeline: [
      { date: "28 Nov 2025", event: "Account opened; insertion line requirement captured" },
      { date: "3 Dec 2025", event: "PI issued" },
      { date: "3 Jan 2026", event: "Background research completed" },
      { date: "8 Jan 2026", event: "Stocking and shipment" },
      { date: "28 Jan 2026", event: "Feeder sliders and solenoid valve spares added" },
      { date: "6 Feb 2026", event: "Batch for vertical and horizontal inserter spares, placement machine parts, wave soldering parts, forming machine parts, nozzle gripper pads" },
      { date: "13 May 2026", event: "Fourth batch: vertical and horizontal inserter spares" },
    ],
    evidence: "Delivery record. Dates from the project system. No pricing, no customer identity.",
  },
  {
    id: "case-17",
    num: "17",
    title: "Wave Soldering Fingers Extended Into ESD Flooring and Cleanroom Entry",
    region: "India",
    industry: "Electronics manufacturing services",
    status: "Delivered",
    statusTone: "done",
    recordedWindow: "Dec 2025 - Mar 2026",
    team: "Jason Wu",
    profile: "An Indian EMS provider running wave soldering lines, buying soldering consumables in batch quantities and upgrading its ESD and cleanroom entry provisions.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/desc/2019/09/Wave-Soldering-Finger-Resin-claw-8.jpg?imageMogr2/thumbnail/960x640/format/webp",
      alt: "Wave soldering machine fingers of the class supplied in a 200-piece order to an Indian EMS provider",
      sourcePage: "https://www.smthelp.com/smickokitianchun-wave-soldering-machine-finger-resin-claw-for-tht-pcb-assembly.html",
    },
    background: "Opened Dec 2025 with a wave soldering consumables enquiry. The interesting part is what happened next: before the first order had shipped, the account had expanded into ESD flooring and air shower entry. That is a small window into how an EMS provider's requirements actually develop, one consumable at a time.",
    challenge: "Wave soldering fingers are a wear item, and the buyer usually knows the machine but not the finger geometry. Getting the wrong profile means a full batch that will not clamp. Alongside that, an EMS provider upgrading its ESD provisions is buying into a standard it has to maintain, not just a product, so the flooring and the entry equipment have to be specified together.",
    solution: "We started by learning the product properly rather than quoting blind. On 13 Dec 2025 the account owner ran a structured study on wave soldering finger types, past sales cases and the marketing approach before replying to the customer. The finger geometry was then matched to the customer's machine and quoted on 10 Jan 2026. The ESD flooring and air shower items were scoped as a separate programme.",
    implementation: "The finger geometry was matched to the customer's machine and quoted on 10 Jan 2026, three days after the spare parts enquiry. Dispatch documentation was issued on 16 Mar 2026 and a PI for 200 L-type fingers followed on 18 Mar 2026. The ESD flooring and air shower requirements were scoped in parallel as a separate programme.",
    metrics: [
      { value: "200 L-type fingers", label: "Order quantity", basis: "Delivery record" },
      { value: "3 (wave soldering, ESD flooring, air shower)", label: "Requirement categories", basis: "Delivery record" },
      { value: "From 7 Jan to 10 Jan 2026", label: "Enquiry to quotation", basis: "Delivery record" },
      { value: "Product study completed 13 Dec 2025", label: "Study before first reply", basis: "Delivery record" },
    ],
    benefits: [
      "Finger geometry matched to the machine before quoting, so the batch fits.",
      "Batch quantity of 200, sized to a maintenance cycle rather than to a minimum order.",
      "ESD flooring and cleanroom entry scoped alongside the soldering consumables.",
      "Product study completed before the first commercial reply, not after.",
    ],
    timeline: [
      { date: "2 Dec 2025", event: "Account opened" },
      { date: "13 Dec 2025", event: "Product study on wave soldering fingers; past case review; ESD flooring enquiry" },
      { date: "15 Dec 2025", event: "Air shower entry enquiry" },
      { date: "7 Jan 2026", event: "Wave soldering spares enquiry" },
      { date: "10 Jan 2026", event: "L-type finger quotation issued" },
      { date: "16 Mar 2026", event: "Dispatch: commercial invoice and packing list" },
      { date: "18 Mar 2026", event: "PI issued for 200 L-type fingers" },
    ],
    evidence: "Delivery record. Dates and quantities from the project system. No pricing, no customer identity.",
  },
  {
    id: "case-18",
    num: "18",
    title: "Wave Soldering Titanium Fingers: A Structured First Response",
    region: "France",
    industry: "Electronics manufacturing services",
    status: "Delivered",
    statusTone: "done",
    recordedWindow: "Jan 2026 - Apr 2026",
    team: "Light Zhan",
    profile: "A French family-owned EMS provider founded in 1983, started by engineers from in-circuit test and still carrying that test culture into its assembly work.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/desc/2020/07/1.jpg?imageMogr2/thumbnail/960x640/format/webp",
      alt: "Titanium wave soldering fingers of the class quoted to a French EMS provider",
      sourcePage: "https://www.smthelp.com/vitronics-l-or-v-type-titanium-wave-soldering-finger.html",
    },
    background: "Enquiry received Jan 2026 for wave soldering titanium fingers. The account was handled by Light Zhan, who did not start with a quotation. The sequence recorded on this account is worth reading as a method: product study, past case review, marketing plan, customer background research, email breakdown, follow-up, then a quotation reply.",
    challenge: "A first reply on a consumable part is where most of these accounts are lost. Quote too early and the finger profile is wrong. Quote too late and the customer has already bought elsewhere. The rep also had to handle the commercial questions that came with the enquiry: pricing queries and logistics questions, both before and after the order.",
    solution: "The rep ran the study sequence first, on 2 Mar 2026: learning the titanium finger product, reviewing the successful sales cases on record, drafting the marketing approach, researching the customer, breaking down the inbound email, and preparing the follow-up. Only then came the quotation reply. When the purchase order arrived on 8 Apr 2026, the PI and the logistics arrangements were handled in the same step.",
    implementation: "The quotation was prepared only after six study steps were completed on 2 Mar 2026. The purchase order arrived on 8 Apr 2026 and the PI and logistics were handled the same day. Commercial and logistics questions raised by the customer were answered before the order, not after it.",
    metrics: [
      { value: "6 completed on 2 Mar 2026", label: "Study steps before quoting", basis: "Delivery record" },
      { value: "About 12 weeks (15 Jan to 8 Apr 2026)", label: "Enquiry to purchase order", basis: "Delivery record" },
      { value: "Same day, 8 Apr 2026", label: "Purchase order to PI", basis: "Delivery record" },
      { value: "Commercial and logistics, both answered before the order", label: "Questions handled", basis: "Delivery record" },
    ],
    benefits: [
      "Six study steps completed before the first quotation, so the finger profile is right.",
      "Past sales cases used as evidence rather than generic claims.",
      "PI and logistics handled the same day the purchase order arrived.",
      "Commercial and logistics questions answered up front, removing the usual second round.",
    ],
    timeline: [
      { date: "15 Jan 2026", event: "Account opened" },
      { date: "2 Mar 2026", event: "Product study on titanium fingers; past sales cases reviewed; marketing plan drafted" },
      { date: "2 Mar 2026", event: "Customer background research; inbound email broken down; follow-up prepared" },
      { date: "2 Mar 2026", event: "Quotation reply prepared, including commercial and logistics questions" },
      { date: "8 Apr 2026", event: "Purchase order received; PI issued; logistics arranged" },
    ],
    evidence: "Delivery record. Dates from the project system. No pricing, no customer identity.",
  },
  {
    id: "case-19",
    num: "19",
    title: "Insertion Machine Re-engagement Extended Into Fixture Cleaning",
    region: "Slovakia",
    industry: "Electronics manufacturing",
    status: "Re-engaged",
    statusTone: "part",
    recordedWindow: "Dec 2025 - Jan 2026",
    team: "Leon Hong",
    profile: "A Central European electronics manufacturer running through-hole insertion equipment, with a recorded run of consecutive orders through 2023 and 2024 before the account went quiet.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/desc/2019/08/SME5200-Fixture-cleaning-machine.png?imageMogr2/thumbnail/960x640/format/webp",
      alt: "Pallet and fixture cleaning machine quoted during the re-engagement of a Central European account",
      sourcePage: "https://www.smthelp.com/sme-5200-aqueous-pallet-cleaning-system-southern-machinery.html",
    },
    background: "The account has a recorded history of nine consecutive orders between Oct 2023 and Oct 2024, then a gap. Leon Hong picked it up again in Dec 2025. The re-engagement did not reopen on the old product line; it came in through a fixture cleaning requirement, which is a different conversation from the one that had gone quiet.",
    challenge: "A lapsed account needs a reason to come back, and reopening on the same product that stalled rarely provides one. The second problem is quoting into a vacuum: with fifteen months of gap, the customer's line configuration may have changed, so quoting against the old specification risks repeating whatever went wrong before.",
    solution: "The rep ran a full re-qualification on 21 Jan 2026 rather than quoting from the old file: background research, requirement capture, product study, then the proposal, then the quotation including freight. The fixture cleaner enquiry was treated as the entry point, and the proposal was built around the customer's current palette and fixture set rather than the 2024 configuration.",
    implementation: "Five re-qualification steps were completed on 21 Jan 2026, and a spare parts order was received the same day. The re-engagement came in through fixture cleaning rather than the product line that had gone quiet, which gave the account a reason to reopen. No production measurements are available for the earlier orders.",
    metrics: [
      { value: "9 consecutive, Oct 2023 to Oct 2024", label: "Historical orders", basis: "Delivery record" },
      { value: "5 completed on 21 Jan 2026", label: "Re-qualification steps", basis: "Delivery record" },
      { value: "New product line used as the entry point", label: "Re-engagement", basis: "Delivery record" },
      { value: "Including freight, prepared same day", label: "Quotation", basis: "Delivery record" },
    ],
    benefits: [
      "Full re-qualification before quoting, so the proposal reflects the current line.",
      "A new product line as the entry point, rather than reopening on the stalled one.",
      "Freight included in the first quotation, removing a second round.",
      "Nine orders of history to work from on specification and packaging.",
    ],
    timeline: [
      { date: "1 Dec 2025", event: "Account reopened" },
      { date: "(Oct 2023 - Oct 2024)", event: "Nine consecutive orders recorded on the account history" },
      { date: "21 Jan 2026", event: "Background research" },
      { date: "21 Jan 2026", event: "Fixture cleaning machine enquiry" },
      { date: "21 Jan 2026", event: "Requirement capture" },
      { date: "21 Jan 2026", event: "Product study" },
      { date: "21 Jan 2026", event: "Proposal issued; quotation including freight prepared" },
      { date: "21 Jan 2026", event: "Spare parts order received" },
    ],
    evidence: "Delivery and re-engagement record. Dates from the project system. No pricing, no customer identity.",
  },
  {
    id: "case-20",
    num: "20",
    title: "Six-Category Supply Relationship Extended Into Laser Welding",
    region: "Mexico",
    industry: "Industrial supply / EMS support",
    status: "Delivered (multi-order), expansion in progress",
    statusTone: "part",
    recordedWindow: "Jul 2025 - Feb 2026",
    team: "Jason Wu",
    profile: "A Mexican industrial supplier and service partner serving EMS plants in Mexico, including a US-based EMS group, buying across wave soldering, insertion, ESD, rework and now laser welding.",
    image: {
      src: "https://hk03-1251009151.file.myqcloud.com/smthelp.com/desc/2016/01/%E5%85%A8%E8%87%AA%E5%8A%A8%E6%B5%B8%E7%84%8A%E6%9C%BA1.jpg?imageMogr2/thumbnail/960x640/format/webp",
      alt: "Wave soldering fingers of the class supplied across a six-category relationship with a Mexican industrial supplier",
      sourcePage: "https://www.smthelp.com/product/china-made-wave-soldering-finger-for-pcba",
    },
    background: "The relationship runs across six product categories already: wave soldering titanium fingers, an offline axial insertion machine with 60 stations delivered to a US EMS group, PCB ESD trolleys, ESD bags, a BGA rework station, and assorted industrial items. In Jan 2026 the customer asked about laser welding equipment, and asked as a potential distributor rather than as an end user.",
    challenge: "Moving an existing supply relationship into distribution changes what the customer needs. As a buyer they want a quotation. As a distributor they need a commercial framework: cooperation terms, a product range, technical documentation, training, and a route to market. Supplying the machine without that framework just creates a support burden.",
    solution: "We built the distributor answer rather than the buyer answer. On 29 and 30 Jan 2026 the work covered the requirement analysis, the machine specification, a technical specification document, a demonstration plan, an initial business meeting, a distributor cooperation proposal, an assessment of the customer's customised training needs, a survey of their installed equipment, and a long-term roadmap. In parallel we kept the existing categories supplied, including an ESD mat enquiry on 4 Feb 2026.",
    implementation: "Six product categories have been supplied through this relationship, including a 60-station offline axial insertion machine delivered to a US EMS group. The Jan 2026 laser welding enquiry was answered with ten distributor workstreams across two days, covering specification, demonstration, cooperation terms, training needs and a roadmap, rather than with a quotation alone.",
    metrics: [
      { value: "6", label: "Product categories supplied", basis: "Delivery record" },
      { value: "60 stations", label: "Offline insertion capacity delivered", basis: "Delivery record" },
      { value: "10 across two days", label: "Distributor workstreams opened", basis: "Delivery record" },
      { value: "2 (Mexico supply, US end user)", label: "Countries served", basis: "Delivery record" },
    ],
    benefits: [
      "Six categories on one relationship, one set of commercial terms.",
      "A 60-station offline insertion line already delivered and working.",
      "Distributor framework built: specification, demonstration, training, cooperation terms.",
      "Existing categories kept supplied while the new one is developed.",
    ],
    timeline: [
      { date: "5 Jul 2025", event: "Earliest record on the account" },
      { date: "(earlier)", event: "Wave soldering titanium fingers supplied" },
      { date: "(earlier)", event: "Offline axial insertion machine, 60 stations, delivered to a US EMS group" },
      { date: "(earlier)", event: "PCB ESD trolley, ESD bags and BGA rework station supplied" },
      { date: "29 Jan 2026", event: "Laser welding equipment enquiry and quotation" },
      { date: "29 Jan 2026", event: "Requirement analysis; installed equipment survey; demonstration plan" },
      { date: "29 Jan 2026", event: "Distributor cooperation proposal and long-term roadmap drafted" },
      { date: "30 Jan 2026", event: "Laser welding enquiry followed up; customised training needs assessed" },
      { date: "30 Jan 2026", event: "Technical specification document prepared; initial business meeting arranged" },
      { date: "4 Feb 2026", event: "ESD mat enquiry" },
    ],
    evidence: "Delivery record. Dates and category counts from the project system. No pricing, no customer identity, no end-user names.",
  },
];

export const PROJECT_CASE_COUNT = PROJECT_CASES.length;

